pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = 'GeoKori'
include ':core'
//include ':ecomap-app'
include ':geokori-app'

include ':google-play-services'

include ':ui:ui-compose'
include ':ui:ui-maplibre'
include ':ui:ui-formatters'
include ':ui:ui-shared'
include ':ui:ui-maplibre-car-app'
include ':car-app'

//Combolite plugins开发支持
include ':plugins:dependencies'
//combolite plugins
include ':plugins:common'
include ':plugins:home'
include ':plugins:setting'
include ':plugins:example'

